/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Tailwind stops at 2xl (1536px), so a 1920 or 2560 display had no breakpoint to
      // aim at and every layout stayed frozen in its 2xl arrangement. These match the two
      // sizes the workspace scale steps at in index.css, so type and layout grow together.
      screens: {
        '3xl': '1920px',
        '4xl': '2560px',
      },
      opacity: {
        8: '0.08',
        12: '0.12',
      },
      spacing: {
        xxs: '0.25rem',
        xs: '0.5rem',
        sm: '0.75rem',
        md: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        xxl: '2rem',
        xxxl: '2.5rem',
      },
      fontSize: {
        caption: ['0.6875rem', { lineHeight: '1rem' }],
        'body-sm': ['0.75rem', { lineHeight: '1.125rem' }],
        body: ['0.875rem', { lineHeight: '1.375rem' }],
        'body-lg': ['1rem', { lineHeight: '1.625rem' }],
        h4: ['1.125rem', { lineHeight: '1.5rem' }],
        h3: ['1.25rem', { lineHeight: '1.75rem' }],
        h2: ['1.5rem', { lineHeight: '2rem' }],
        h1: ['1.875rem', { lineHeight: '2.375rem' }],
      },
      borderRadius: {
        control: '0.5rem',
        surface: '0.75rem',
        panel: '1rem',
      },
      minHeight: {
        controlSm: '2rem',
        controlMd: '2.5rem',
        controlLg: '3rem',
      },
      minWidth: {
        controlSm: '2rem',
        controlMd: '2.5rem',
        controlLg: '3rem',
      },
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        card: 'rgb(var(--surface) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--surface-elevated) / <alpha-value>)',
        'surface-muted': 'rgb(var(--surface-muted) / <alpha-value>)',
        'surface-soft': 'rgb(var(--surface-muted) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--muted-foreground) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-soft': 'rgb(var(--border-soft) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--primary-foreground) / <alpha-value>)',
        'primary-strong': 'rgb(var(--primary-strong) / <alpha-value>)',
        'primary-muted': 'rgb(var(--primary-muted) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        'secondary-foreground': 'rgb(var(--secondary-foreground) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--accent-foreground) / <alpha-value>)',
        success: 'rgb(var(--success) / <alpha-value>)',
        warning: 'rgb(var(--warning) / <alpha-value>)',
        destructive: 'rgb(var(--destructive) / <alpha-value>)',
        info: 'rgb(var(--info) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',
        ink: 'rgb(var(--foreground) / <alpha-value>)',
        charcoal: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        slate: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        steel: 'rgb(var(--muted-foreground) / <alpha-value>)',
        stone: 'rgb(var(--muted) / <alpha-value>)',
        canvas: 'rgb(var(--background) / <alpha-value>)',
        hairline: 'rgb(var(--border) / <alpha-value>)',
        'hairline-soft': 'rgb(var(--border) / <alpha-value>)',
        coral: 'rgb(var(--destructive) / <alpha-value>)',
        magenta: '#ea5ec1',
        minimaxBlue: 'rgb(var(--primary) / <alpha-value>)',
        cyan: 'rgb(var(--info) / <alpha-value>)',
        purple: '#a855f7',
        brand: {
          50: 'rgb(var(--primary-soft) / <alpha-value>)',
          100: 'rgb(var(--primary-soft) / <alpha-value>)',
          300: 'rgb(var(--primary-muted) / <alpha-value>)',
          400: 'rgb(var(--primary-muted) / <alpha-value>)',
          500: 'rgb(var(--primary) / <alpha-value>)',
          600: 'rgb(var(--primary-strong) / <alpha-value>)',
          700: 'rgb(var(--primary-strong) / <alpha-value>)',
        }
      }
    },
  },
  plugins: [],
}
