import React, { useState } from 'react'
import { Check, Search, X } from 'lucide-react'
import { Button } from '../../components/ui/Button'
import { Input } from '../../components/ui/Input'
import { Select } from '../../components/ui/Select'
import { Textarea } from '../../components/ui/Textarea'
import { useTheme, type ThemePreference } from '../../theme/ThemeProvider'

export default function UiCatalogPage() {
  const { theme, setTheme } = useTheme()
  const [value, setValue] = useState('one')
  const [checked, setChecked] = useState(true)
  return <main className="min-h-screen bg-background p-md text-foreground sm:p-xxl"><div className="mx-auto max-w-5xl space-y-xxl"><header className="flex flex-wrap items-end justify-between gap-md border-b border-border pb-lg"><div><p className="text-caption font-semibold uppercase tracking-wider text-muted-foreground">Development only</p><h1 className="text-h1 font-semibold">UI control catalog</h1><p className="mt-xs text-body text-muted-foreground">Reference every control size, state, focus treatment, and both theme modes.</p></div><Select value={theme} onChange={event => setTheme(event.target.value as ThemePreference)} aria-label="Theme" className="w-40"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></Select></header>
    <section className="grid gap-lg rounded-panel border border-border bg-surface p-lg md:grid-cols-3"><h2 className="md:col-span-3 text-h3 font-semibold">Buttons</h2>{(['sm', 'md', 'lg'] as const).map(size => <div key={size} className="space-y-sm"><p className="text-caption font-mono text-muted-foreground">{size}</p><div className="flex flex-wrap gap-xs"><Button className={`ui-button-${size}`}>Primary</Button><Button variant="secondary" className={`ui-button-${size}`}>Secondary</Button><Button variant="danger" className={`ui-button-${size}`}>Danger</Button><Button disabled className={`ui-button-${size}`}>Disabled</Button></div></div>)}</section>
    <section className="grid gap-lg rounded-panel border border-border bg-surface p-lg md:grid-cols-3"><h2 className="md:col-span-3 text-h3 font-semibold">Fields</h2>{(['sm', 'md', 'lg'] as const).map(size => <div key={size} className="space-y-sm"><p className="text-caption font-mono text-muted-foreground">{size}</p><Input aria-label={`${size} input`} placeholder="Placeholder" className={`ui-control-${size}`} /><Select aria-label={`${size} select`} size={size} value={value} onChange={event => setValue(event.target.value)}><option value="one">Option one</option><option value="two">Option two</option><option value="three">Option three</option></Select></div>)}</section>
    <section className="grid gap-lg rounded-panel border border-border bg-surface p-lg md:grid-cols-2"><div className="space-y-sm"><h2 className="text-h3 font-semibold">Textareas and states</h2><Textarea aria-label="Example textarea" placeholder="Write a note…" /><Textarea aria-label="Disabled textarea" disabled value="Disabled state" readOnly /></div><div className="space-y-md"><label className="flex min-h-controlLg items-center gap-sm rounded-control border border-border bg-input px-md text-body"><input type="checkbox" checked={checked} onChange={event => setChecked(event.target.checked)} className="size-4 accent-primary" /><span>Checkbox: {checked ? 'selected' : 'not selected'}</span></label><div className="flex items-center gap-sm"><button type="button" className="ui-icon-button border border-border bg-surface hover:bg-surface-soft" aria-label="Search"><Search size={16} /></button><button type="button" className="ui-icon-button border border-border bg-surface hover:bg-surface-soft" aria-label="Close"><X size={16} /></button><span className="inline-flex min-h-controlSm items-center gap-xxs rounded-control bg-success/10 px-sm text-body-sm font-semibold text-success"><Check size={14} /> Status badge</span></div></div></section>
  </div></main>
}
